version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  # ADD THIS SECTION:
  jobs:
    post_install:
      - apt-get update && apt-get install -y texlive-latex-extra texlive-fonts-recommended latexmk

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
