[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Otics Advanced Analytics, Inc."
authors = [{name = "Otics", email = "support@otics.ca"}]
dynamic = ["version", "description"]
